### ISSUE TITLE
[Error] jekyll build fails with liquid exception using 'none' for max_width after upgrade to 1.4.1

### ISSUE THREAD

**Issue by sethlbrown** [heychirag/jekyll-google-photos#9]
Hello! First of all, thank you for maintaining this wonderful gem of a gem. I've used it on multiple sites. After a recent bundle update, I started seeing a new error that seems to point back to line 24 in tag.rb. 

The error occurs when I go to build the site. I'm using bundler, so `bundle exec jekyll build` 

I believe this error began when I upgraded with `bundle udpate` to the 1.4.1 version of the plugin.

The error message with the top part of the stack trace is as follows:

```   
  Rendering Liquid: 03-bikes.html
/Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:17: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
  Liquid Exception: string not matched in 03-bikes.html
jekyll 3.8.7 | Error:  string not matched
Traceback (most recent call last):
        58: from /Users/sethbrown/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
        57: from /Users/sethbrown/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
        56: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
        55: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        54: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
        53: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
        52: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        51: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
        50: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        49: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        48: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        47: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
        46: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
        45: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
        44: from /Users/sethbrown/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
        43: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
        42: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
        41: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/exe/jekyll:15:in `<top (required)>'
        40: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        39: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        38: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        37: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        36: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        35: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        34: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `start'
        33: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `each'
        32: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `block in start'
        31: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:36:in `process'
        30: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:65:in `build'
        29: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/command.rb:28:in `process_site'
        28: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:71:in `process'
        27: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:192:in `render'
        26: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:471:in `render_pages'
        25: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:471:in `each'
        24: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:472:in `block in render_pages'
        23: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:479:in `render_regenerated'
        22: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:62:in `run'
        21: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:79:in `render_document'
        20: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:126:in `render_liquid'
        19: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        18: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        17: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        16: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        15: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        14: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        13: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        12: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        11: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        10: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
         9: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         8: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:84:in `render'
         7: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:84:in `each'
         6: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:85:in `block in render'
         5: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:19:in `getImageLinks'
         4: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `each'
         3: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `upto'
         2: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:238:in `block in each'
         1: from /Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:23:in `block in getImageLinks'
/Users/sethbrown/Sites/woc-bike/vendor/bundle/ruby/2.7.0/gems/jekyll-google-photos-1.4.1/lib/jekyll-google-photos/tag.rb:23:in `[]=': string not matched (IndexError)
```

Here's a code snippet from 03-bikes.html indicating how I'm invoking the plugin on my Jekyll site.

```
<a name="road"></a>
<a href="#top">Back to top</a>
<h2>Road Bikes</h2>
<div id="google-photos2">
  <p>
    The following road bikes are currently available as project stock from the
    bike pile. Check back soon as we add sizes and prices. In the meantime, if
    you're interested in a particular bike, please give us a call.
  </p>
  {% google_photos https://photos.app.goo.gl/MxhGDu87H7jg6mY79 none %}
  <script>
    let galleryRoadBikesHTML = "";
    $.each(googlePhotos.urls, function renderPhotos(index, value) {
      galleryRoadBikesHTML += ` <a
            data-fancybox="gallery"
            href="${value}=w975"
          >
            <img
                src="${value}=w300"
                alt="Bike for Sale"
                width="300"
                border="0"
                class="google-gallery-image"
              />
          </a>
       `;
    });
    $("#google-photos2").append(galleryRoadBikesHTML);
  </script>
</div>
```

**Comment by heychirag** [comment]
Thanks for reporting the issue @sethlbrown . Looks like Google has changed their page layout and that's what causing the problem. I'll try to work on a fix soon.

**Comment by sethlbrown** [comment]
You're a scholar and a gentleman. Let me know if I can make a financial contribution to help out.

**Comment by heychirag** [comment]
@sethlbrown That won't be necessary. Let me know if the new version works fine. Please consider starring the project if you liked it.

**Comment by sethlbrown** [comment]
Yay, this worked! The new Bikes page is up and looking good at http://wocbikeproject.org/bikes

Thanks again!
